apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: kafka-port
      port: 9092
      nodePort: 30192
      targetPort: 9092
    - name: kafka-port-2
      port: 29092
      nodePort: 30292
      targetPort: 29092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      volumes:
      - name: kafka-storage
        persistentVolumeClaim:
          claimName: kafka-pvc
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: '0'
        - name: KAFKA_TOOLS_LOG4J_LOGLEVEL
          value: ERROR
        image: confluentinc/cp-kafka:7.3.0
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
        - containerPort: 29092
        volumeMounts:
        - name: kafka-storage
          mountPath: /home/appuser/test
