apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: duong05102002/py-producer:vlastest
          imagePullPolicy: IfNotPresent
          name: producer
          env:
            - name: BOOTSTRAP_SERVER
              value: kafka-service:9092
          ports:
            - containerPort: 2002
